[package]
name = "wombo"
version = "0.1.0"
authors = ["Justin Duplessis <drfoliberg@gmail.com>"]

[dependencies]
rustc-serialize = "0.3"
bincode = "0.3.0"
num_cpus = "0.2.10"

[[bin]]
path = "src/main/rust/main.rs"
name = "wombo"
